In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
collated_df = pd.read_csv("Collated.csv")

In [3]:
collated_df.head()

TB3MS  T10Y3MM  T10Y2YM  FEDFUNDS  BAA10YM  AAA10YM
0   7.64     0.31     0.12      8.23     1.73     0.78
1   7.74     0.47     0.10      8.24     1.67     0.75
2   7.90     0.42    -0.04      8.28     1.62     0.78
3   7.77     0.75     0.07      8.26     1.51     0.67
4   7.74     0.75     0.12      8.18     1.65     0.71

In [4]:
collated_df['TB3MS'].mean()

2.7629940119760477

In [5]:
collated_df['TB3MS'].std()

2.2888810791648027

In [6]:
collated_df['T10Y3MM'].mean()


1.8267664670658685

In [7]:
collated_df['T10Y3MM'].std()

1.1151828352828081

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()


In [9]:
scaler.fit(collated_df)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
collated_scaled = scaler.transform(collated_df)

In [11]:
print("per feature minimum before scaling:\n {}".format(collated_df.min(axis=0)))

per feature minimum before scaling:
 TB3MS       0.01
T10Y3MM    -0.70
T10Y2YM    -0.41
FEDFUNDS    0.07
BAA10YM     1.29
AAA10YM     0.64
dtype: float64


In [9]:
print("per feature minimum after scaling:\n {}".format(collated_scaled.min(axis=0)))

per feature minimum after scaling:
 [ 0.  0.  0.  0.  0.  0.]


In [12]:
from sklearn.decomposition import PCA

In [13]:
pca = PCA(n_components=1)
pca.fit(collated_scaled)

PCA(copy=True, iterated_power='auto', n_components=1, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [14]:
collated_pca = pca.transform(collated_scaled)

In [15]:
collated_pca

array([[ 1.05175368],
       [ 1.05563864],
       [ 1.08932866],
       [ 1.0592421 ],
       [ 1.03307692],
       [ 1.044678  ],
       [ 0.99694537],
       [ 0.91474923],
       [ 0.87245377],
       [ 0.81442528],
       [ 0.78871113],
       [ 0.72221399],
       [ 0.59464158],
       [ 0.5294432 ],
       [ 0.52655205],
       [ 0.47335481],
       [ 0.41591687],
       [ 0.43315374],
       [ 0.42805846],
       [ 0.37096967],
       [ 0.33862985],
       [ 0.26529943],
       [ 0.14205306],
       [ 0.01320936],
       [-0.0373532 ],
       [-0.02007057],
       [ 0.05495032],
       [-0.04623136],
       [-0.0601385 ],
       [-0.06871434],
       [-0.22222442],
       [-0.22201466],
       [-0.29188512],
       [-0.30391587],
       [-0.22358212],
       [-0.18231516],
       [-0.2262276 ],
       [-0.22614765],
       [-0.20477659],
       [-0.2192937 ],
       [-0.18334571],
       [-0.11664236],
       [-0.09805038],
       [-0.04568699],
       [-0.02606934],
       [-0

In [16]:
print(pca.components_)

[[ 0.5079544  -0.36231401 -0.44476372  0.51977742 -0.20551261 -0.31700491]]


In [26]:
pca.components_.sum()

-0.30186342180084735